export const _CONSTRUCTION  = '/'
export const _LANDING       = '/landing'
export const _CONTACT       = '/contact'
export const _PROJECTS      = '/projects'
export const _RESUME        = '/resume'
export const _DOWNLOADS     = '/downloads'
export const _ACCOLADES     = '/accolades'
export const _ASSETS        = '/assets'
